version: '3.4'
services:
  {{ cookiecutter.dockercompose_service_name }}:
    build:
      context: ../
      dockerfile: services/{{ cookiecutter.project_slug }}/Dockerfile
      cache_from:
        - itisfoundation/{{ cookiecutter.project_slug }}:cache
        - services_{{ cookiecutter.dockercompose_service_name }}:latest
      target: production
      labels: 
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "https://github.com/ITISFoundation/osparc-simcore"
        org.label-schema.vcs-ref: "${VCS_REF}"
    ports:
      - '{{ cookiecutter.dockercompose_service_api_port }}:8080'
    environment:
      - APIHUB_HOST=apihub
      - APIHUB_PORT=8043
    stdin_open: true
    tty: true
    depends_on:
      - apihub
volumes:
  input:
  output:
  log:
  postgres:
