openapi: 3.0.0
info:
  title: {{ cookiecutter.distribution_name }} API
  version: {{ cookiecutter.version }}
  description: API definition for {{ cookiecutter.distribution_name }} service
  contact:
    name: IT'IS Foundation
    email: support@simcore.io
  license:
    name: MIT
    url: https://github.com/ITISFoundation/osparc-simcore/blob/master/LICENSE
servers:
  - description: API server
    url: '/{{ cookiecutter.openapi_specs_version }}'
  - description: Development server
    url: http://{host}:{port}/{basePath}
    variables:
      host:
        default: 'localhost'
      port:
        default: '8001'
      basePath:
        enum:
          - {{ cookiecutter.openapi_specs_version }}
        default: {{ cookiecutter.openapi_specs_version }}
paths:

  # DIAGNOSTICS ---------------------------------------------------------
  /:
    $ref: './openapi-diagnostics.yaml#/paths/~1'

  /check/{action}:
    $ref: './openapi-diagnostics.yaml#/paths/~1check~1{action}'


components:
  responses:
    DefaultErrorResponse:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: './components/schemas/error.yaml#/ErrorEnveloped'
